server:
  port: 8083

spring:
  application:
    name: analytic-service

  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: analytics_user
    password: analytics_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

analytics:
  producer:
    base-url: http://localhost:8082
  consumer:
    base-url: http://localhost:8084

logging:
  level:
    root: INFO
    com.example.analytics: DEBUG

