name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ishimwegabin
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: |
          # Build and push each service
          docker build -t ishimwegabin/integration-mock-service:latest ./mock-service
          docker build -t ishimwegabin/integration-producer:latest ./integration-producer
          docker build -t ishimwegabin/integration-consumer-service:latest ./consumer-service
          docker build -t ishimwegabin/integration-analytic-service:latest ./analytic-service

          docker push ishimwegabin/integration-mock-service:latest
          docker push ishimwegabin/integration-producer:latest
          docker push ishimwegabin/integration-consumer-service:latest
          docker push ishimwegabin/integration-analytic-service:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 222
          script: |
            cd ~/integration-system
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f
